### ISSUE TITLE
Update sensor yaml formatting

### ISSUE THREAD

**Issue by Wardy125** [Eikkargh/Candy-API-to-JSON#1]
First of all, thank you for this - I tried something like this a few years ago, and couldn't for the life of me get the key out.

Just a note to say, the yaml for command line sensors has [changed](https://www.home-assistant.io/blog/2023/06/07/release-20236/#backward-incompatible-changes), and so the expected format for your docs would be

```yaml
command_line:
  - sensor:
      name: 'Candy Washer Dryer'
      scan_interval: 60
      command_timeout: 30
      command: python3 python_scripts/candy.py
      value_template: '{{ value_json }}'
      json_attributes:
        - WiFiStatus
        - Err
        - MachMd
        - Pr
        - PrPh
        - Temp
        - SpinSp
        - RemTime
        - DryT
        - DelVal
        - TotalTime
```

I can update on a new branch and open a PR if you'd like?
