### ISSUE TITLE
Add support for H3DS4965TACBE-80 Washer/Dryer

### ISSUE THREAD

**Issue by BenGlossop09** [Eikkargh/Candy-API-to-JSON#5]
I've compiled a list of the programs on my machine, for reference they are;
PrNm = 
15 = High Heat (dry setting)
14 = Low Heat (dry setting)
13 = Dry Wool (dry setting)
12 = Extra Care
11 = All in One 59'
10 = Rapid 14'/30'/44'
9 = Wool & Soft Care
8 = Rinse
7 = Drain & Spin
6 = Synthetic & Colours
5 = Eco 20C
4 = Cottons & Prewash
3 = Eco 40-60
2 = Cottons
Wifi Setting = No specific PrNm as far as I can tell

I've added them into the configuration.yaml as follows:

```
  - sensor:
      - name: 'Washer/Dryer - Program'
        icon: mdi:progress-star
        state: >
          {% set Prog = state_attr('sensor.candy_washer_dryer', 'PrNm') %}
          {% if Prog == "2" %}Cotton
          {% elif Prog == "3" %}Eco 40-60
          {% elif Prog == "4" %}Cotton & Prewash
          {% elif Prog == "9" %}Wool & Soft Care
          {% elif Prog == "10" %}Rapid 14'/30'/44'
          {% elif Prog == "11" %}All in One 59'
          {% elif Prog == "12" %}Extra Care
          {% elif Prog == "13" %}Dry (Wool)
          {% elif Prog == "14" %}Dry (Low Heat)
          {% elif Prog == "15" %}Dry (High Heat)
          {% elif Prog == None %}Off
          {% else %}{{ Prog }}
          {% endif %}
```

Both before and after making the above changes to the config file, the program entity remains in the 'Off' state at all times. I also added 'Nm' to the state attribute on line 5 of the above code, that didn't change anything. In candy.py 'Pr' and 'PrNm' are set as equals, as far as I understand at least. 

Can I get some more information which could shine light on why the program numbers are not being used correctly?

**Comment by Eikkargh** [comment]
Excellent, thank you for the program codes. Ill create another configuration.yaml to match the settings for your machine.

My notes suggest I added line 54 for testing. You can either comment this line out:
<code>if k == 'PrNm': k == 'Pr'</code>
Or edit your .yaml command_line sensor attribute Pr instead of PrNm and the template back to:
```
- sensor:
      - name: 'Washer/Dryer - Program'
        icon: mdi:progress-star
        state: >
          {% set Prog = state_attr('sensor.candy_washer_dryer', 'Pr') %}
          #etc
```

**Comment by Eikkargh** [comment]
If you have no luck there are 2 other hoover/ candy integrations on HACS that are more robust than mine. I created this project because neither one worked for my machine at the time. As my first Python project its very much just muddled together in the simplest way possible. It worked so I have not checked the others recently but they are still under development.
<a href="https://github.com/ofalvai/home-assistant-candy">Candy Simpy-Fi</a> 
<a href="https://github.com/Andre0512/hon">Haier hOn</a>
Although I use the Hoover Wizard app both of the above use the same hardware so should work in theory.

**Comment by BenGlossop09** [comment]
I managed to get it working! I changed all references of 'Pr' to 'PrNm' and reloaded all yaml (in developer tools). I also have had no luck with Haier hOn. Candy Simpy-Fi works well for me but your solution gives far more information. 
![Screenshot 2024-09-16 094302](https://github.com/user-attachments/assets/01ebe666-f0f5-4794-9dd6-d71fcd0af8dd)
configuration.yaml:
```
command_line:
  - sensor:
      name: 'Candy Washer Dryer'
      scan_interval: 60
      command_timeout: 30
      command: python3 ./pyscript/candy.py
      value_template: '{{ value_json }}'
      json_attributes:
        - WiFiStatus
        - Err
        - MachMd
        - PrNm
        - PrPh
        - Temp
        - SpinSp
        - RemTime
        - DryT
        - DelVal
        - TotalTime
```

```
  - sensor:
      - name: 'Washer/Dryer - Program'
        icon: mdi:progress-star
        state: >
          {% set Prog = state_attr('sensor.candy_washer_dryer', 'PrNm') %}
```

and candy.py
```
url = 'http://192.168.4.38/http-read.json?encrypted=1'
key = 'mnlkbhjdlbelcgkc'
request_timeout = 10
retries = 3
retry_delay = 2
candyOff = {'WiFiStatus':'1', 'Err':None, 'MachMd':None, 'PrNm':None, 'PrPh':None, 'Temp':None, 'SpinSp':None, 'RemTime':'0', 'DryT':'0', 'DelVal':0, 'TotalTime':'0'}
tries = 0
candy = {}
```

Further changes I have made;
Changed default 'No Error' code to 0 - 0 is no error for my machine.
My machine outputs remaining time in seconds so I have added a divide by 60 to Remaining Time and Total Time. Note remaining time shows as xx.x instead of xx minutes, I should add a truncation to solve this. 

Outstanding issues;
Not much of an issue but the only feature not supported in the PrNm list is the WiFi setting. It doesn't appear to hold a unique value. I have not yet tested what the program entity will output when WiFi is selected and a wash is started - I would assume the machine will output the actual program selected. 
Rapid 14'/30'/44' do not each hold a unique program so are bundled together. 
Add commands?
